# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: tetris
version: '0.0.0'
github: "lierdakil/tetris"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: tetris is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - gloss
  - vector
  - random
  - filepath
  - directory
  - binary
  - bytestring
  - string-interpolate
  - req
  - retry
  - containers
  - stm
  - async
  source-dirs: library

executables:
  tetris:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - tetris
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
